# -*- coding: utf-8 -*-
"""Cartilha_Funcoes_DEV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKWS0CVhdUNTO24dhJVTygtUbPYaYsHo

### Funções em Python
"""

# Uma função serve pra "encapsular" um bloco de codigo
# Isso permite reaproveitar codigo, organizar melhor, e tambem "esconder" tarefas secundarias que
# não estão relacionadas ao programa que voce esta escrvendo

# Função sem retorno

# primeiro: declaramos a função UMA VEZ:
# DECLARAÇÃO DA FUNÇÃO (CRIAÇÃO):

def dizer_ola():
    print("Olá mundo")

# UTILIZAÇÃO (CHAMADA) DA FUNÇÃO:
dizer_ola()
dizer_ola()
dizer_ola()
dizer_ola()

# Funções com parametros
# Os parentesis serve para passar parâmetros(argumentos) para a função
# vamos declarar uma funcao que recebe o nome da pessoa e o sobrenome e diz olá pra ela

# DECLARAÇÃO DA FUNÇÃO COM ENTRADA DE PARÂMETROS:
def dizer_ola_personalizado(nome , sobrenome):
    print("Olá," , nome,sobrenome)

# CHAMADA DA FUNÇÃO EM UM PROGRAMA
nome = input("Digite seu nome: ")
sobrenome = input("Digite seu sobrenome: ")

# dizer_ola_personalizado() ---> isso vai dar erro: faltando 2 argumentos

dizer_ola_personalizado(nome,sobrenome)

# Vamos declarar uma funcao media() que recebe 3 numeros e retorna a media para o programa
# este retorno deverá ser tratado pelo programa, ou então se perderá
# no nosso exemplo, vamos armazena-lo em uma variavel chamada media
# primeiro vamos ver como ficaria o programa SEM USAR funções:

nome_aluno = input("Nome aluno: ")
nota1 = float(input("digite a nota 1: "))
nota2 = float(input("digite a nota 2: "))
nota3 = float(input("digite a nota 3: "))

media = (nota1 + nota2 + nota3) / 3

print(f"MEDIA FINAL DO ALUNO {nome_aluno} : {media:.2f} ")

# agora vamos "embalar" o calculo da media em uma função:

# DECLARAÇÃO DA FUNCAO
def media(n1,n2,n3):  # funcao com argumentos POSICIONAIS
    return (n1+n2+n3)/3

# CHAMADA DA FUNÇÃO
nome_aluno = input("Nome aluno: ")
nota1 = float(input("digite a nota 1: "))
nota2 = float(input("digite a nota 2: "))
nota3 = float(input("digite a nota 3: "))

media = media(nota1,nota2,nota3) # o retorno da função vai ser gravado na variavel media

print(f"MEDIA FINAL DO ALUNO {nome_aluno} : {media:.2f} ")

# Vamos criar uma função com um argumento de palavra-chave e opcional
# Ela vai receber nome e sobrenome e dizer ola personalizado. se ela nao receber nada, imprimirá Olá Mundo

def dizer_ola_turbinado( nome_usuario = "mundo" ):
    print("Ola" , nome_usuario )

dizer_ola_turbinado()

dizer_ola_turbinado("Anderson")

dizer_ola_turbinado("Jorge")

dizer_ola_turbinado()

dizer_ola_turbinado( nome_usuario = "Marcelo")

# Agora vamos incluir um argumento de palavra-chave vazio, se a funcao receber um valor,
# ela irá usar, senao, não irá usar

def dizer_ola_clima( clima = '' , nome_usuario = "mundo"  ):
    if clima:
        print("Ola" , nome_usuario, " o clima atual é: " , clima )
    else:
        print("Ola", nome_usuario )

dizer_ola_clima()
dizer_ola_clima("banana") # encaixa no primeiro argumento da função
dizer_ola_clima( nome_usuario = "banana" )
dizer_ola_clima( "calor" , "Anderson")
dizer_ola_clima( nome_usuario = "Anderson" , clima = "calor")

# Funcao Lambda:

# imagine a seguinte funcao :
def somar(numero1 , numero2):
    return numero1 + numero2

print( somar(8,9) )

# eu posso transforma-la eu uma funcao lambda deste jeito:
# variavel = lambda <parametros> : <retorno>

somar_lambda = lambda num1,num2 : num1 + num2

print( somar_lambda(5,7) )

"""🧪 Exercícios de Funções em Python

📘 Nível 1 – Fundamentos

✅ Exercício 1: Criando sua primeira função
Crie uma função chamada boas_vindas que apenas imprime a mensagem:
"Bem-vindo ao nosso sistema!"
"""

def boas_vindas():
 print ("Bem-vindo ao nosso sistema!")

boas_vindas()

"""✅ Exercício 2: Função com parâmetro
Crie uma função chamada cumprimentar que receba um nome como parâmetro e
imprima:
"Olá, [nome]!"
"""

def cumprimento(nome):
  print(f"Olá, {nome}!")

nome = input("Digite seu nome: ")
cumprimento(nome)

"""✅ Exercício 3: Função com dois parâmetros
Crie uma função chamada apresentar que receba um nome e uma idade, e exiba
a mensagem:
"Olá, me chamo [nome] e tenho [idade] anos."
"""

def apresentar(nome,idade):
  print(f"Olá, me chamo {nome} e tenho {idade} anos.")

nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
apresentar(nome,idade)

"""✅ Exercício 4: Função que retorna resultado
Crie uma função chamada soma que receba dois números e retorne a soma
deles.
Armazene o resultado em uma variável e exiba-o com print .
"""

def soma(num1,num2):
  return num1 + num2

num1 = float(input("Digite um número: "))
num2 = float(input("Digite outro número: "))
resultado = soma(num1,num2)

print (f"O resultado é {resultado}.")

"""✅ Exercício 5: Função que verifica se é maior de idade
Crie uma função chamada eh_maior que recebe uma idade como parâmetro e
retorna:

"Maior de idade" se for 18 ou mais

"Menor de idade" se for menor
"""

def eh_maior(idade):
  if idade >= 18:
    return "Maior de idade"
  else:
    return "Menor de idade"

idade = int(input("Digite sua idade: "))
print(eh_maior(idade))

"""📗 Nível 2 – Trabalhando com lógica

✅ Exercício 6: Função que calcula o quadrado de um número
Crie uma função chamada quadrado que receba um número e retorne o valor ao
quadrado.
"""

def potencia_ao_quadrado(num):
  return num ** 2

num = float(input("Digite um número: "))
print(potencia_ao_quadrado(num))

"""✅ Exercício 7: Função que recebe uma tupla e retorna a média
Crie uma função chamada media_notas que recebe uma tupla com duas notas e
retorne a média.
"""

def media_notas(notas):
  return sum(notas) / len(notas)

notas = (float(input("Digite a primeira nota: ")), float(input("Digite a segunda nota: ")))
print('A sua nota foi: ', media_notas(notas))

"""✅ Exercício 8: Função que recebe um dicionário e imprime os
valores

Crie uma função chamada exibir_dados que recebe um dicionário com:

nome

idade

curso

A função deve exibir os dados formatados, um por linha.
"""

def exibir_dados(nome, idade, curso):
  print(f"Nome: {nome}")
  print(f"Idade: {idade}")
  print(f"Curso: {curso}")
  return

nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
curso = input("Digite seu curso: ")
exibir_dados(nome, idade, curso)

"""✅ Exercício 9: Função que recebe uma lista de nomes e
imprime um por um
Crie uma função chamada listar_nomes que recebe uma lista de nomes e imprime
cada nome da lista.
"""

def listar_nomes():
  nomes = []
  while True:
    nome = input("Digite um nome: ")
    if nome == "":
      break
    nomes.append(nome)
  for nome in nomes:
    print(nome)
  return

listar_nomes()

"""🚀 Exercício 10: DESAFIO – Função "Caixa Eletrônico"
Crie uma função chamada caixa_eletronico que:

Recebe um valor (número inteiro)

Retorna a quantidade de notas de R100, R50, R20 e R10 necessárias
para formar o valor

Utilize divmod() para facilitar a conta

📌 Exemplo:

caixa_eletronico(280)
# Retorna: 2 notas de 100 reais, 1 nota de 50 reais, 1 nota de 20 reais, 1 nota de 10 reais
"""

def caixa_eletronico(valor):
    notas = [100, 50, 20, 10, 5, 2]
    resultado = []

    for nota in notas:
        qtd, valor = divmod(valor, nota)
        if qtd > 0:
            resultado.append(f"{qtd} nota(s) de R${nota}")

    return "\n".join(resultado)

valor = int(input("Digite o valor a ser sacado: "))
print(caixa_eletronico(valor))