# -*- coding: utf-8 -*-
"""Exercicios_print_input_variaveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rtYQ0QOMqpbLI4wuWWoR1STOO9mf9dDA

**Exercício 1: Registro de Informações Pessoais**

Desenvolva um programa em Python que solicite ao usuário que insira seu nome, sobrenome e idade. Em seguida, o programa deve exibir uma mensagem de boas-vindas contendo essas informações.

Utilize os comandos print, input e variáveis para capturar e exibir os dados fornecidos pelo usuário.
"""

nome = input (' Qual seu primeiro nome? ')
sobrenome = input (' Qual seu sobrenome? ')
idade = input (' Qual sua idade? ')

print ('Bem-vindo ' + nome , sobrenome + ' de ' + idade , 'anos' + '!')

"""**Exercício 2: Calculadora de média**

Crie um programa em Python que solicite ao usuário que insira as notas das três provas. Em seguida, o programa deve calcular a média dessas notas e exibir o resultado para o usuário.

Certifique-se de utilizar os comandos print, input e variáveis para realizar a operação.
"""

nota1 = float (input (' Qual sua primeira nota? '))
nota2 = float (input (' Qual sua segunda nota? '))
nota3 = float (input (' Qual sua terceira nota? '))

media_geral = ((nota1 + nota2 + nota3)/3)
print (f'Sua média geral é: {media_geral:.2f}')

"""**Exercício 3: Conversor de Tempo**

Crie um programa em Python que solicite ao usuário um valor em **dias**. Em seguida, o programa deve converter esse valor para **horas, minutos e segundos** e exibir o resultado para o usuário.

✅ Utilize os comandos `print`, `input` e variáveis para capturar e exibir os dados.

✅ Considere que **1 dia tem 24 horas, 1 hora tem 60 minutos e 1 minuto tem 60 segundos**.


"""

dias = int (input('Quantos dias? '))

horas = dias * 24 #dias para horas
minutos = horas * 60 #horas para minutos
segundos = minutos * 60 #minutos para segundos

print (f'São {horas} horas, {minutos} minutos e {segundos} segundos.')

"""### **Exercício 4: Cadastro de Informações e Conversão de Idade**

Crie um programa em Python que:

1. Solicite ao usuário seu **nome, sobrenome e idade**.
2. Converta a idade informada em diferentes unidades de tempo:
    - **Meses** (1 ano = 12 meses)
    - **Semanas** (1 ano = 52 semanas)
    - **Dias** (1 ano = 365 dias)
    - **Horas** (1 dia = 24 horas)
    - **Minutos** (1 hora = 60 minutos)
    - **Segundos** (1 minuto = 60 segundos)
3. Exiba todas essas informações organizadas de maneira clara.

✅ O programa deve utilizar `print`, `input` e **cálculos matemáticos** para realizar as conversões.
"""

nome = input (' Qual seu primeiro nome? ')
sobrenome = input (' Qual seu sobrenome? ')
idadeAno = int (input(' Qual sua idade? '))

meses = idadeAno * 12 # ano para meses
semana = idadeAno * 52 # ano para semanas
dias = idadeAno * 365 # ano para dias
horas = idadeAno * 365 * 24 # ano para horas
minutos = idadeAno * 365 * 24 * 60 #ano para minutos
segundos = idadeAno * 365 * 24 * 60 * 60 #ano para segundos

print (f'Olá {nome}! Sua idade corresponde a {meses} meses, {semana} semanas, {dias} dias, {horas} horas e {minutos} minutos e {segundos} segundos.')

"""### **Exercício 5: Conversor de Moeda**

Crie um programa que solicite ao usuário um valor em **reais (R$)** e uma cotação do **dólar (USD)**. O programa deve converter o valor inserido para dólares e exibir o resultado.
"""

valor_reais = float (input('Quantos reais? '))

cotacao_dolar = 5

dolar_conversao = valor_reais / cotacao_dolar

print (f'Você tem {dolar_conversao:.2f} dólares.')

"""### **Exercício 6: Cálculo do Tempo de Viagem**

Crie um programa que solicite ao usuário a **distância em km** e a **velocidade média do veículo em km/h**. O programa deve calcular e exibir o **tempo estimado da viagem** em horas e minutos.
"""

distancia_km = float (input('Digite a distância da viagem (km):  '))
velocidade_media = float (input('Digite a velocidade média (km/h): '))

tempo = distancia_km / velocidade_media

print (f'O tempo de viagem será de {tempo:.2f} horas.')

"""### **Exercício 7: Cálculo de Área e Perímetro de um Retângulo**

Crie um programa que solicite a **largura** e **altura** de um retângulo e calcule sua **área** e **perímetro**.
"""

largura = float (input('Digite a largura do retângulo (m): '))
altura = float (input('Digite a altura do retângulo (m): '))

area = largura * altura
perimetro = 2 * (largura + altura)

print (f'Área: {area} m². Perímetro: {perimetro} m.')

"""### **Exercício 8: Cálculo do IMC**

Crie um programa que solicite o **peso (kg)** e a **altura (m)** de uma pessoa, calcule o **Índice de Massa Corporal (IMC)** e classifique o resultado conforme a tabela do IMC.
"""

peso = float (input('Digite seu peso (kg): '))
altura = float (input('Digite sua altura (m): '))

imc = peso / (altura ** 2)

print (f'O seu IMC(Índice de Massa Corporal) é de {imc:.2f}.')

"""### **Exercício 9: Cálculo do Troco**

Crie um programa que solicite o **valor da compra** e o **valor pago pelo cliente**. O programa deve calcular e exibir o **troco a ser devolvido**.
"""

valorCompra = float (input('Digite o valor da compra: '))
valorPago = float (input('Digite o valor pago: '))

troco = valorPago - valorCompra

print (f'O troco a ser devolvido é R$ {troco:.2f}')

"""### **Exercício 10: Conversor de Temperatura**

Crie um programa que solicite uma **temperatura em graus Celsius (°C)** e a converta para **Fahrenheit (°F)**.
"""

temperaturaCelsius = float (input('Digite a temperatura em Celsius: '))

fahrenheit = (temperaturaCelsius * 9/5) + 32

print (f'{temperaturaCelsius:.2f} C° equivalem a {fahrenheit:.2f} F°.')