# -*- coding: utf-8 -*-
"""Exercícios_de_For.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtOBmdl1bQL8w-QzQEpFxtctfxLGmCGt

# Exercícios

## 1. Criando um Registro de Hóspedes

Digamos que você está criando o sistema para registrar a chegada de hóspedes em um hotel. No hotel, os hóspedes podem ter quartos com 1, 2, 3 e 4 pessoas. Seu sistema deve conseguir:

1. Identificar quantas pessoas o hóspede que acabou de chegar vai ter no quarto (perguntando por meio de input)
2. De acordo com a quantidade de pessoas do hóspede, ele deve fazer um for para perguntar o cpf e o nome de cada pessoa, a fim de registrá-la no quarto (2 inputs para cada pessoa, 1 para o cpf e outro para o nome)
3. O seu programa então deve gerar uma lista com todas as pessoas que ficarão no quarto em que cada item dessa lista é o nome da pessoa e o cpf da pessoa, assim:

quarto = [
    ['João', 'cpf:00000000000'],
    ['Julia', 'cpf:11111111111'],
    ['Marcus', 'cpf:22222222222'],
    ['Maria', 'cpf:33333333333'],
]

- Para simplificar, não vamos nos preocupar com possibilidades de "tentar colocar mais de 1 hóspede, digitar o cpf errado, etc. Nosso objetivo é treinar a criação de uma rotina de cadastro
"""

hospede = int(input('Quantas pessoas? '))
quarto = []

for i in range(hospede):
    nome = input('Nome? ')
    cpf = input('CPF? ')
    quarto.append((nome, cpf))

print(quarto)

"""## 2. Análise de Vendas

Nesse exercício vamos fazer uma "análise simples" de atingimento de Meta.

Temos uma lista com os vendedores e os valores de vendas e queremos identificar (printar) quais os vendedores que bateram a meta e qual foi o valor que eles venderam.
"""

meta = 10000
vendas = [
    ['João', 15000],
    ['Julia', 27000],
    ['Marcus', 9900],
    ['Maria', 3750],
    ['Ana', 10300],
    ['Alon', 7870],
]
#seu código aqui
for venda in vendas:
    if venda[1] >= meta:
        print(f"{venda[0]} bateu a meta com R${venda[1]:,.2f}")

"""## 3. Comparação com Ano Anterior

Digamos que você está analisando as vendas de produtos de um ecommerce e quer identificar quais produtos tiveram no ano de 2020 mais vendas do que no ano de 2019, para reportar isso para a diretoria.

Sua resposta pode ser um print de cada produto, qual foi a venda de 2019, a venda de 2020 e o % de crescimento de 2020 para 2019.

Lembrando, para calcular o % de crescimento de um produto de um ano para o outro, podemos fazer: (vendas_produto2020/vendas_produto2019 - 1)

Dica: lembre do enumerate, ele pode facilitar seu "for"
"""

produtos = ['iphone', 'galaxy', 'ipad', 'tv', 'máquina de café', 'kindle', 'geladeira', 'adega', 'notebook dell', 'notebook hp', 'notebook asus', 'microsoft surface', 'webcam', 'caixa de som', 'microfone', 'câmera canon']
vendas2019 = [558147,712350,573823,405252,718654,531580,973139,892292,422760,154753,887061,438508,237467,489705,328311,591120]
vendas2020 = [951642,244295,26964,787604,867660,78830,710331,646016,694913,539704,324831,667179,295633,725316,644622,994303]
#seu código aqui
for i, produto in enumerate(produtos):
   v2019 = vendas2019[i]
   v2020 = vendas2020[i]

if v2020 > v2019:

     crescimento = (v2020 / v2019) - 1
     print(f"{produto.capitalize()}:")
     print(f"  Vendas 2019: {v2019}")
     print(f"  Vendas 2020: {v2020}")
     print(f"  Crescimento: {crescimento:.2%}\n")

indice_mais_vendido_2019 = vendas2019.index(max(vendas2019))
produto_mais_vendido_2019 = produtos[indice_mais_vendido_2019]

indice_mais_vendido_2020 = vendas2020.index(max(vendas2020))
produto_mais_vendido_2020 = produtos[indice_mais_vendido_2020]

print("Produto mais vendido em 2019:")
print(f"{produto_mais_vendido_2019.capitalize()} com {vendas2019[indice_mais_vendido_2019]} unidades\n")

print("Produto mais vendido em 2020:")
print(f"{produto_mais_vendido_2020.capitalize()} com {vendas2020[indice_mais_vendido_2020]} unidades")

"""4. Contando a Grana da Feira
Situação: Você foi na feira comprar frutas. Anote os preços das frutas que comprou:
[2.50, 3.00, 1.75, 4.20, 3.30]

Desafio: Crie um código que use for para somar o total gasto na feira.




"""

frutas = [2.50, 3.00, 1.75, 4.20, 3.30]
# Seu código aqui
total = 0

for fruta in frutas:
  total += fruta

print(f"O total gasto na feira foi de R${total:.2f}")

"""5.Repetindo Senha Segura
Situação: Um sistema precisa gerar uma senha segura repetindo uma palavra com um número de vezes definido pelo usuário.

Desafio: Peça uma palavra e um número. Use for para repetir a palavra esse número de vezes.
"""

palavra = input("Digite uma palavra para sua senha: ")
vezes = int(input("Quantas vezes repetir? "))
# Seu código aqui
senha = ""

for i in range(vezes):
  senha += palavra

print(senha)

"""6.Contagem Regressiva para o Lançamento
Situação: Você trabalha na NASA e precisa fazer a contagem regressiva para o lançamento de um foguete 🚀

Desafio: Faça um código que conte de 10 até 0 usando for e no final exiba "Decolar!"
"""

import time

lista_numeros = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

for numero in lista_numeros:
  print(numero)
  time.sleep(1)
  if numero == 0:
    print('Decolar!')

"""7. Lista de Presença da Galera
Situação: Você é monitor(a) de uma turma e precisa registrar quem está presente.

Desafio: Dada a lista de alunos, use for para exibir cada nome com a mensagem "presente".
"""

alunos = ["Ana", "Bruno", "Carlos", "Daniela", "Eduardo"]
# Seu código aqui
for presenca in alunos:
  print(f"{presenca} presente!")

"""8.  Tabuada Ninja
Situação: Seu dojo de matemática quer ensinar tabuada de forma ninja!

Desafio: Peça um número ao usuário e use for para exibir a tabuada dele de 1 a 10.
"""

numero = int(input("Digite um número para ver a tabuada: "))
# Seu código aqui
for i in range(1, 11):
  print(f"{numero} x {i} = {numero * i}")

"""9. Contando Vogais de uma Palavra
Situação: Você está criando um jogo de palavras e precisa contar as vogais de uma palavra.

Desafio: Peça uma palavra e use for para contar quantas vogais ela tem.
"""

palavra = input("Digite uma palavra: ").lower()
# Seu código aqui
contador = 0
for letra in palavra:
  if letra in 'aeiou':
    contador += 1
print(f"A palavra {palavra} tem {contador} vogais")

"""10. Corrida dos Robôs
Situação: Uma corrida de robôs tem 5 voltas. Cada robô registra seu tempo por volta.

Desafio: Crie um programa que peça o tempo de cada volta (em segundos), use for para somar o total e diga o tempo total da corrida.
"""

total = 0
for volta in range(1, 6):
    tempo = float(input(f"Tempo da volta {volta}: "))
    # Some ao total
    total += tempo
    # Mostre o tempo total
    print(f"Tempo total: {total:.2f} segundos")

"""🍭 Desafio Final: Fábrica de Pirulitos
🏭 Situação-problema:

Você foi contratado(a) por uma fábrica de pirulitos para desenvolver um sistema que simule a produção do dia.
Cada pirulito produzido é representado por um emoji 🍭.

🛠️ Regras:
O usuário informa quantos pirulitos foram produzidos em cada hora do expediente (8 horas de trabalho).

Use um laço for para:

Pedir a quantidade de pirulitos de cada hora.

Exibir uma “barrinha de produção” visual com 🍭 repetidos.
"""

## Exemplo

for hora in range(1, 9):
    qtd = int(input(f"Quantos pirulitos foram feitos na hora {hora}? "))
    print(f"Hora {hora}: " + "🍭" * qtd)

##✅ Saída esperada:
Quantos pirulitos foram feitos na hora 1? 3
Hora 1: 🍭🍭🍭
Quantos pirulitos foram feitos na hora 2? 5
Hora 2: 🍭🍭🍭🍭🍭
...