# -*- coding: utf-8 -*-
"""Exercicios_metodo_format.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGgaJmSVyTlM6WF-uEW9XlDYubuR2bjL

## **Exercícios  - Metódo .format**

## Crie programas em python para atender as especificações abaixo.

# 1 - Faça um programa que peça o nome de um país, a capital e o idioma oficial e exiba uma mensagem com essas informações.
"""

pais = input ('Digite um país: ')
capital = input ('Digite sua capital: ')
idioma = input ('Digite seu idioma: ')

print('Seu país é {}, capital {}, idioma {}'.format(pais, capital, idioma))

"""# 2 - Escreva um programa que peça dois números e exiba a soma deles."""

numeroUm = float (input ('Digite o primeiro a ser somado: '))
numeroDois = float (input ('Digite o segundo numero a ser somado: '))

resultadoSoma = numeroUm + numeroDois

print('A soma de {} e {} resulta em {}.' .format(numeroUm, numeroDois, resultadoSoma))

"""# 3 - Faça um programa que solicite o nome e a idade do usuário e exiba uma mensagem personalizada."""

nomeUsuario= (input ('Digite o seu nome: '))
idadeUsuario = (input ('Digite a sua idade: '))

mensagem = 'Seja bem-vindo'

print( '{} {} de {} anos.' .format(mensagem, nomeUsuario, idadeUsuario))

"""# 4 - Crie duas variáveis para armazenar valores numéricos e exiba o resultado da soma."""

numeroUm = float (input ('Digite o primeiro a ser somado: '))
numeroDois = float (input ('Digite o segundo numero a ser somado: '))

resultadoSoma = numeroUm + numeroDois

print('A soma de {} e {} resulta em {}.' .format(numeroUm, numeroDois, resultadoSoma))

"""# 5 -  Escreva um programa que peça o nome do usuário e exiba uma mensagem de boas-vindas."""

nomeUsuario= (input ('Digite o seu nome: '))

mensagem = 'Seja bem-vindo'

print( '{} {}.' .format(mensagem, nomeUsuario))

"""#  6 - Você foi contratado para desenvolver um programa que auxilie um petshop a gerar mensagens personalizadas para seus clientes. O programa deve solicitar algumas informações do cliente e, em seguida, exibir uma mensagem customizada com base nos dados fornecidos.

O programa deve conter as seguintes etapas:

Solicitar ao usuário que digite seu nome, o nome do seu pet (animal de estimação) e a espécie do pet (por exemplo, cachorro, gato, pássaro, etc.).

Em seguida, peça ao usuário que informe a idade do pet em anos.

Solicite também ao usuário que informe se o pet já tomou todas as vacinas obrigatórias (responda com "Sim" ou "Não").

Com base nas informações coletadas, o programa deve gerar uma mensagem personalizada para o cliente. A mensagem deve incluir o nome do cliente, o nome do pet, a espécie do pet, sua idade em anos e se já tomou todas as vacinas obrigatórias.
"""

nomeUsuario = (input ('Digite o seu nome: '))
nomeAnimalDeEstimacao = (input ('Digite o seu nome do seu animal de estimação: '))
especieAnimalDeEstimacao = (input ('Digite a espécie do seu animal de estimação (por exemplo, cachorro, gato, pássaro, etc.): '))
idadeAnimalDeEstimacao = (input ('Digite a idade em anos do seu animal de estimação: '))
vacinaAnimalDeEstimacao = (input ('O animal de estimação já tomou todas as vacinas obrigatórias? Responda com SIM ou NÃO '))


print( 'Olá {} dono do {}, espécie {}, idade de {} anos, vacinado: {}.' .format(nomeUsuario, nomeAnimalDeEstimacao, especieAnimalDeEstimacao, idadeAnimalDeEstimacao, vacinaAnimalDeEstimacao ))

