# -*- coding: utf-8 -*-
"""Introducao_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBnrL2fwaviyY1vaILrd0GT8mcZ2GQIu
"""

print ("Olá mundo!")
print ('Hello world!')
print (123)
print (2 / 1)

faturamento = 150
custo = 60
lucro = faturamento - custo
print (lucro)

nota1 = 10
nota2 = 9.5
nota3 = 9
media_geral = ((nota1 + nota2 + nota3)/3)
print (media_geral)

input ('Qual seu nome?')

nome = input ('Qual seu nome? ')

print (nome)