# -*- coding: utf-8 -*-
"""missaopythonenigma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198r-3aYjx0sRUK56iDlsiZNFSyrD0q_v

### ☔ **Contexto**

Você foi contratado como **programador júnior da Agência Secreta** para desenvolver um sistema de codificação de mensagens. O sistema precisa transformar palavras comuns em códigos secretos, usando um método simples: **cada letra será substituída pela próxima na tabela ASCII**.

Seu trabalho é criar um programa que:

✅ Peça 3 palavras do usuário (de até 5 letras cada).

✅ Codifique cada letra **manual e individualmente** (sem laços).

✅ Junte as letras codificadas e mostre a mensagem final com uma **formatação bonita**.

✅ Use **`ord()`** e **`chr()`**, **acesso por índice** (`palavra[0]`) e **f-string** ou `.format()` na saída.

---

## 📚 Parte 1 – Pesquisa Obrigatória:

Antes de começar, anote no caderno ou arquivo:

1. O que `ord()` faz em Python?

 R: Ele retorna o valor inteiro do código Unicode de um caractere.

2. O que `chr()` faz?
  
  R: Ele faz o inverso do ord(), convertendo um código Unicode de volta para um caractere.
3. Como transformar uma string em uma lista de letras? (ex: `list("texto")`)

 R: Para transformar uma string em uma lista de letras em Python, use list(string). Exemplo:

 `lista = list("Python")  # Resultado: ['P', 'y', 't', 'h', 'o', 'n']`

 Alternativas:
 Compreensão de lista: [letra for letra in string]

 Operador *: [*string]

4. O que são f-strings? Dê um exemplo com variáveis.

 R: As f-strings (formatted string literals) são uma forma simples e eficiente de formatar strings em Python (a partir da versão 3.6). Elas permitem inserir variáveis e expressões diretamente dentro de strings usando { }.

5. Como acessar letras específicas de uma string com índice (`palavra[0]`, etc)?

 R: As strings são sequências imutáveis de caracteres, e você pode acessar letras individuais usando índices (posições).

6. O que acontece se tentarmos acessar uma letra que não existe (ex: `palavra[6]` em uma palavra com só 4 letras)?

 R: Se tentar acessar um índice que não existe, Python retorna um erro:

 `print(palavra[10])  # IndexError: string index out of range`

7. O que é a  **tabela ASCII**.?

 R: A ASCII (American Standard Code for Information Interchange) é um padrão de codificação que mapeia caracteres (letras, números, símbolos) em números binários (valores de 0 a 127). Criada na década de 1960, foi uma das primeiras formas de representar texto em computadores.

## Parte 2 – Mão na massa

### Exemplo de como codificar uma letra:

```python
letra = "a"
codigo = ord(letra)
letra_codificada = chr(codigo + 1)
print(letra_codificada)  # saída: b

```

---

## ✅ Regras do programa:

- Use `input()` para pedir 3 palavras (até 5 letras).
- Separe letra por letra usando `palavra[0]`, `palavra[1]`, etc.
- Aumente 1 no código ASCII com `ord() + 1` e converta de volta com `chr()`.
- Reconstrua cada palavra codificada e junte as 3 palavras numa frase.
- Formate a saída com **f-string** ou `.format()` (obrigatório).
- **Não use for nem while.**
"""

primeiraPalavra = input('Digite a primeira palavra com até 5 letras: ').strip()[:5]
segundaPalavra = input('Digite a segunda palavra com até 5 letras: ').strip()[:5]
terceiraPalavra = input('Digite a terceira palavra com até 5 letras: ').strip()[:5]

primeiraPalavraLetra1 = primeiraPalavra[0]
primeiraPalavraLetra2 = primeiraPalavra[1]
primeiraPalavraLetra3 = primeiraPalavra[2]
primeiraPalavraLetra4 = primeiraPalavra[3]
primeiraPalavraLetra5 = primeiraPalavra[4]

segundaPalavraLetra1 = segundaPalavra[0]
segundaPalavraLetra2 = segundaPalavra[1]
segundaPalavraLetra3 = segundaPalavra[2]
segundaPalavraLetra4 = segundaPalavra[3]
segundaPalavraLetra5 = segundaPalavra[4]

terceiraPalavraLetra1 = terceiraPalavra[0]
terceiraPalavraLetra2 = terceiraPalavra[1]
terceiraPalavraLetra3 = terceiraPalavra[2]
terceiraPalavraLetra4 = terceiraPalavra[3]
terceiraPalavraLetra5 = terceiraPalavra[4]


resultadoCodificado = (ord(primeiraPalavraLetra1)+1,
                       ord(primeiraPalavraLetra2)+1,
                       ord(primeiraPalavraLetra3)+1,
                       ord(primeiraPalavraLetra4)+1,
                       ord(primeiraPalavraLetra5)+1)

resultadoDescodificado = (chr(resultadoCodificado[0]-1) +
                          chr(resultadoCodificado[1]-1) +
                          chr(resultadoCodificado[2]-1) +
                          chr(resultadoCodificado[3]-1) +
                          chr(resultadoCodificado[4]-1))


print("\nPalavras digitadas:")
print(primeiraPalavra, segundaPalavra, terceiraPalavra)

print("\nCodificação da primeira palavra (valores ASCII + 1):")
print(resultadoCodificado)

print("\nDecodificação (revertendo os valores):")
print(resultadoDescodificado)

print("\nLetras isoladas:")
print(
    primeiraPalavraLetra1,
    primeiraPalavraLetra2,
    primeiraPalavraLetra3,
    primeiraPalavraLetra4,
    primeiraPalavraLetra5,
    segundaPalavraLetra1,
    segundaPalavraLetra2,
    segundaPalavraLetra3,
    segundaPalavraLetra4,
    segundaPalavraLetra5,
    terceiraPalavraLetra1,
    terceiraPalavraLetra2,
    terceiraPalavraLetra3,
    terceiraPalavraLetra4,
    terceiraPalavraLetra5,
)