# -*- coding: utf-8 -*-
"""TUPLA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12XOhVuhVm3cXrrNR_2KdMoaqZZiEgM2K

🧠 Nível 1 – Fundamentos

✅ Exercício 1: Criando um dicionário com tupla

Crie um dicionário chamado aluno com os seguintes dados:

nome: "Lucas"

idade: 17

cursos: uma tupla com os cursos "Matemática" e "Python Básico"

Depois, mostre os dados na tela, incluindo o segundo curso da tupla.
"""

aluno = {
    "nome": "Lucas",
    "idade": 17,
    "cursos": ("Matemática", "Python Básico")
}

print("Nome:", aluno["nome"])
print("Idade:", aluno["idade"])
print("Cursos:", aluno["cursos"])
print("Segundo curso:", aluno["cursos"][1])

"""✅ Exercício 2: Acessando dados da tupla

Utilize o dicionário do exercício anterior para mostrar apenas:

O nome do aluno

O primeiro curso da tupla
"""

aluno = {
    "nome": "Lucas",
    "idade": 17,
    "cursos": ("Matemática", "Python Básico")
}

print("Nome do aluno:", aluno["nome"])
print("Primeiro curso:", aluno["cursos"][0])

"""✅ Exercício 3: Alterando valores e adicionando chave com
tupla
No dicionário aluno faça:

Altere a idade para 18

Adicione a chave "disciplinas_favoritas" com uma tupla: "Python" e "Algoritmos"


Depois, exiba o dicionário completo.


"""

aluno = {
    "nome": "Lucas",
    "idade": 17,
    "cursos": ("Matemática", "Python Básico")
}

aluno["idade"] = 18

aluno["disciplinas_favoritas"] = ("Python", "Algoritmos")

print(aluno)

"""✅ Exercício 4: Usando .get() para acesso seguro

Tente acessar a chave "nota_final" do dicionário usando o método .get() .

Caso a chave não exista, exiba a mensagem "Nota ainda não cadastrada."

📌 Dica: .get("chave", "mensagem padrão") evita erros se a chave não existir.
"""

nota = aluno.get("nota_final", "Nota ainda não cadastrada.")

print(nota)

"""✅ Exercício 5: Remover chave com del
Remova a chave "disciplinas_favoritas" do dicionário.
Depois, mostre o dicionário atualizado.

"""

del aluno["disciplinas_favoritas"]

print(aluno)

"""🧩 Nível 2 – Trabalhando com listas e tuplas

✅ Exercício 6: Lista de compras com tupla

Crie uma tupla de produtos com três itens.

Depois, crie um dicionário compras onde:

Cada produto da tupla é uma chave

O valor é a quantidade comprada

Percorra a tupla e mostre quantos itens de cada produto foram comprados.
"""

produtos = ("Arroz", "Feijão", "Macarrão")

compras = {
    "Arroz": 2,
    "Feijão": 1,
    "Macarrão": 3
}

for produto in produtos:
    print(f"{produto}: {compras[produto]} unidades")

"""✅ Exercício 7: Lista de alunos (com notas em tupla)

Crie uma lista turma com 3 dicionários, um para cada aluno.

Cada dicionário deve conter:

nome

idade

notas : tupla com duas notas

Percorra a lista e mostre o nome de cada aluno e sua média de notas.

"""

turma = [
    {"nome": "Lucas", "idade": 17, "notas": (8.0, 7.5)},
    {"nome": "Ana", "idade": 16, "notas": (9.0, 8.5)},
    {"nome": "Carlos", "idade": 18, "notas": (6.0, 7.0)}
]

for aluno in turma:
    nome = aluno["nome"]
    notas = aluno["notas"]
    media = sum(notas) / len(notas)
    print(f"{nome} - Média: {media:.1f}")

"""✅ Exercício 8: Média geral da turma

Usando os dados da lista turma , calcule a média geral das notas de todos os
alunos juntos.
"""

turma = [
    {"nome": "Lucas", "idade": 17, "notas": (8.0, 7.5)},
    {"nome": "Ana", "idade": 16, "notas": (9.0, 8.5)},
    {"nome": "Carlos", "idade": 18, "notas": (6.0, 7.0)}
]

soma_notas = 0
quantidade_notas = 0

for aluno in turma:
    notas = aluno["notas"]
    soma_notas += sum(notas)
    quantidade_notas += len(notas)

media_geral = soma_notas / quantidade_notas
print(f"Média geral da turma: {media_geral:.1f}")

"""✅ Exercício 9: Maior nota da turma

Percorra os alunos e descubra quem tirou a maior nota individual (de qualquer
posição da tupla).

Mostre o nome do aluno e o valor da nota.
"""

turma = [
    {"nome": "Lucas", "idade": 17, "notas": (8.0, 7.5)},
    {"nome": "Ana", "idade": 16, "notas": (9.0, 8.5)},
    {"nome": "Carlos", "idade": 18, "notas": (6.0, 7.0)}
]

maior_nota = 0
aluno_com_maior_nota = ""

for aluno in turma:
    for nota in aluno["notas"]:
        if nota > maior_nota:
            maior_nota = nota
            aluno_com_maior_nota = aluno["nome"]

print(f"A maior nota foi {maior_nota} e foi tirada por {aluno_com_maior_nota}.")

"""🚀 Exercício 10: DESAFIO – Mini sistema de
biblioteca com tuplas

Crie um pequeno programa onde o usuário possa cadastrar livros, sendo que
cada livro deve conter:

título

autor

ano de publicação

📌 Cada livro será salvo como uma tupla: (título, autor, ano)
Todos os livros devem ser guardados em uma lista chamada biblioteca .

Ao final, exiba todos os livros cadastrados no formato:

📚 Livros cadastrados:

1. Título: Dom Casmurro | Autor: Machado de Assis | Ano: 1899
2. ...
"""

# Lista que vai armazenar os livros cadastrados
biblioteca = []

# Laço para cadastrar livros
while True:
    # Solicitar dados do livro
    titulo = input("Digite o título do livro: ")
    autor = input("Digite o autor do livro: ")
    ano = int(input("Digite o ano de publicação: "))

    # Salvar o livro como uma tupla e adicionar na lista biblioteca
    livro = (titulo, autor, ano)
    biblioteca.append(livro)

    # Perguntar se o usuário quer cadastrar outro livro
    continuar = input("Deseja cadastrar outro livro? (s/n): ").lower()
    if continuar != 's':
        break

# Exibir os livros cadastrados
print("\n📚 Livros cadastrados:")
for livro in biblioteca:
    print(f"Título: {livro[0]} | Autor: {livro[1]} | Ano: {livro[2]}")